// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpWsIb_4noBHzav3uwnNAmrOqICT0SbTM',
    appId: '1:752814044347:web:110fbc1a72332c9982659e',
    messagingSenderId: '752814044347',
    projectId: 'weight-logger-63577',
    authDomain: 'weight-logger-63577.firebaseapp.com',
    storageBucket: 'weight-logger-63577.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjPznu5B4fkjdGTQt28MbMHGkSNa1sv-o',
    appId: '1:752814044347:android:bdbb2f9bf15ed7fe82659e',
    messagingSenderId: '752814044347',
    projectId: 'weight-logger-63577',
    storageBucket: 'weight-logger-63577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBujIz0rrcysSj16DMEQClfH1yyPZvJK5A',
    appId: '1:752814044347:ios:3224500f0d0325a882659e',
    messagingSenderId: '752814044347',
    projectId: 'weight-logger-63577',
    storageBucket: 'weight-logger-63577.appspot.com',
    iosBundleId: 'com.example.weightLogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBujIz0rrcysSj16DMEQClfH1yyPZvJK5A',
    appId: '1:752814044347:ios:3224500f0d0325a882659e',
    messagingSenderId: '752814044347',
    projectId: 'weight-logger-63577',
    storageBucket: 'weight-logger-63577.appspot.com',
    iosBundleId: 'com.example.weightLogger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpWsIb_4noBHzav3uwnNAmrOqICT0SbTM',
    appId: '1:752814044347:web:4009cca4d416572c82659e',
    messagingSenderId: '752814044347',
    projectId: 'weight-logger-63577',
    authDomain: 'weight-logger-63577.firebaseapp.com',
    storageBucket: 'weight-logger-63577.appspot.com',
  );

}